"""create dummy table

Revision ID: 3
Revises: 2
Create Date: 2023-08-09 03:51:48.319499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('txn_dttm', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('prv_txn_id', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('order_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('command', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('sum', sa.DECIMAL(), nullable=True))
    op.create_index(op.f('ix_payments_account_id'), 'payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_payments_command'), 'payments', ['command'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_prv_txn_id'), 'payments', ['prv_txn_id'], unique=False)
    op.create_index(op.f('ix_payments_sum'), 'payments', ['sum'], unique=False)
    op.create_index(op.f('ix_payments_txn_dttm'), 'payments', ['txn_dttm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_txn_dttm'), table_name='payments')
    op.drop_index(op.f('ix_payments_sum'), table_name='payments')
    op.drop_index(op.f('ix_payments_prv_txn_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_command'), table_name='payments')
    op.drop_index(op.f('ix_payments_account_id'), table_name='payments')
    op.drop_column('payments', 'sum')
    op.drop_column('payments', 'command')
    op.drop_column('payments', 'account_id')
    op.drop_column('payments', 'order_id')
    op.drop_column('payments', 'prv_txn_id')
    op.drop_column('payments', 'txn_dttm')
    # ### end Alembic commands ###
